"use client"

import { useEffect, useState } from "react"
import { Check, Loader2, QrCode, Sparkles } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog"

type Plan = { id: string; name: string; duration_days: number; price_vnd: number }
type Payment = { transaction: { transaction_code: string }; qr_code_url: string; bank_info: { bank_name: string; account_no: string; account_name: string; amount: number; content: string } }

export function InterviewSubscriptionDialog({ open, onOpenChange }: { open: boolean; onOpenChange: (open: boolean) => void }) {
  const [plans, setPlans] = useState<Plan[]>([])
  const [loadingPlan, setLoadingPlan] = useState<string | null>(null)
  const [payment, setPayment] = useState<Payment | null>(null)
  const [paymentCompleted, setPaymentCompleted] = useState(false)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    if (!open || plans.length) return
    void fetch('/api/interview/plans', { cache: 'no-store' })
      .then((response) => response.json())
      .then((payload) => setPlans(payload.plans || []))
      .catch(() => setError('Không thể tải danh sách gói'))
  }, [open, plans.length])

  useEffect(() => {
    if (!open || !payment?.transaction.transaction_code || paymentCompleted) return
    let stopped = false
    let checking = false
    const verify = async () => {
      if (checking || stopped) return
      checking = true
      try {
        const response = await fetch('/api/payment/verify', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ transaction_code: payment.transaction.transaction_code }),
        })
        const payload = await response.json()
        if (response.ok && payload.status === 'completed') {
          stopped = true
          setPaymentCompleted(true)
          window.setTimeout(() => window.location.reload(), 1200)
        }
      } finally {
        checking = false
      }
    }
    const intervalId = window.setInterval(() => void verify(), 3000)
    void verify()
    return () => {
      stopped = true
      window.clearInterval(intervalId)
    }
  }, [open, payment?.transaction.transaction_code, paymentCompleted])

  async function createPayment(planId: string) {
    setLoadingPlan(planId)
    setError(null)
    setPaymentCompleted(false)
    try {
      const response = await fetch('/api/interview/payment/create', {
        method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ plan_id: planId }),
      })
      const payload = await response.json()
      if (!response.ok) throw new Error(payload.error || 'Không thể tạo mã thanh toán')
      setPayment(payload)
    } catch (reason) {
      setError(reason instanceof Error ? reason.message : 'Không thể tạo mã thanh toán')
    } finally {
      setLoadingPlan(null)
    }
  }

  return (
    <Dialog open={open} onOpenChange={(next) => { onOpenChange(next); if (!next) { setPayment(null); setPaymentCompleted(false) } }}>
      <DialogContent className="max-h-[96dvh] gap-2.5 overflow-y-auto rounded-[22px] p-3 sm:max-h-[92dvh] sm:max-w-4xl sm:gap-4 sm:rounded-3xl sm:p-7">
        <DialogHeader className="items-center gap-0.5 px-5 text-center sm:gap-1 sm:px-0">
          <div className="mb-0.5 inline-flex w-fit items-center gap-1.5 rounded-full bg-violet-50 px-2 py-0.5 text-[9px] font-black uppercase tracking-wide text-violet-700 ring-1 ring-violet-100 sm:mb-1 sm:px-2.5 sm:py-1 sm:text-[10px]">
            <Sparkles className="size-3" /> Lộ trình Phỏng vấn Vòng 2
          </div>
          <DialogTitle className="text-lg font-extrabold tracking-tight sm:text-2xl sm:font-black">Chinh phục Vòng 2</DialogTitle>
          <DialogDescription className="max-w-xl text-xs leading-4 sm:text-sm sm:leading-5">Chọn thời hạn phù hợp với kế hoạch luyện tập của bạn.</DialogDescription>
        </DialogHeader>
        {paymentCompleted ? (
          <div className="flex flex-col items-center gap-3 rounded-2xl bg-emerald-50 px-5 py-10 text-center ring-1 ring-emerald-100">
            <span className="flex size-14 items-center justify-center rounded-full bg-emerald-600 text-white"><Check className="size-7" /></span>
            <strong className="text-xl font-black text-emerald-950">Thanh toán thành công</strong>
            <p className="text-sm text-emerald-800">Gói Phỏng vấn Vòng 2 đã được kích hoạt. Đang cập nhật quyền học…</p>
          </div>
        ) : payment ? (
          <div className="grid gap-5 sm:grid-cols-[220px_1fr] sm:items-center">
            {/* QR is generated by VietQR from the exact SePay transfer details. */}
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img alt="Mã QR thanh toán gói Phỏng vấn Vòng 2" className="mx-auto w-full max-w-[220px] rounded-2xl border" src={payment.qr_code_url} />
            <div className="space-y-2 rounded-2xl bg-slate-50 p-4 text-sm">
              <div className="flex items-center gap-2 font-bold text-blue-700"><QrCode className="size-4" /> Quét QR để thanh toán</div>
              <p><b>Số tiền:</b> {payment.bank_info.amount.toLocaleString('vi-VN')}đ</p>
              <p><b>Nội dung:</b> <span className="font-mono font-bold">{payment.bank_info.content}</span></p>
              <p className="text-xs leading-5 text-slate-500">Giữ nguyên nội dung chuyển khoản. SePay sẽ tự kích hoạt và cộng dồn thời hạn sau khi ngân hàng xác nhận.</p>
            </div>
          </div>
        ) : (
          <div>
            <div className="grid items-stretch gap-2 sm:grid-cols-3 sm:gap-3">
              {plans.map((plan) => {
                const recommended = plan.duration_days === 30
                const pricePerDay = Math.round(plan.price_vnd / plan.duration_days)
                const description = plan.duration_days === 1
                  ? 'Ôn cấp tốc trước ngày phỏng vấn.'
                  : plan.duration_days === 10
                    ? 'Luyện trọng tâm trong thời gian ngắn.'
                    : 'Luyện toàn diện và cải thiện điểm yếu.'
                return (
                  <article className={`relative flex flex-col overflow-hidden rounded-2xl border p-3 text-left transition hover:-translate-y-0.5 hover:shadow-lg sm:min-h-[230px] sm:p-5 ${recommended ? 'border-violet-500 bg-gradient-to-br from-violet-50 to-blue-50 ring-1 ring-violet-100 sm:ring-2' : 'border-slate-200 bg-white'}`} key={plan.id}>
                    {recommended ? <span className="absolute right-2.5 top-2.5 rounded-full bg-violet-600 px-2 py-0.5 text-[8px] font-black uppercase tracking-wide text-white sm:right-3 sm:top-3 sm:py-1 sm:text-[9px]">Khuyên dùng</span> : null}
                    <strong className="text-base font-extrabold text-slate-950 sm:text-lg sm:font-black">{plan.duration_days} ngày</strong>
                    <p className="mt-0.5 truncate pr-1 text-[11px] leading-4 text-slate-600 sm:mt-1 sm:min-h-10 sm:whitespace-normal sm:text-xs sm:leading-5">{description}</p>
                    <div className="mt-2 flex items-end justify-between gap-2 sm:mt-3 sm:gap-3">
                      <p className="text-[22px] font-extrabold leading-none text-violet-700 sm:text-3xl sm:font-black">{plan.price_vnd.toLocaleString('vi-VN')}đ</p>
                      <span className="text-[9px] font-semibold text-slate-500 sm:pb-1 sm:text-[10px]">≈ {pricePerDay.toLocaleString('vi-VN')}đ/ngày</span>
                    </div>
                    {recommended ? <p className="mt-1 truncate text-[9px] font-bold text-emerald-700 sm:text-[10px]">Tiết kiệm khoảng 48.000đ so với gói ngắn hạn</p> : null}
                    <Button className={`mt-2 h-9 w-full rounded-xl text-xs font-extrabold sm:mt-auto sm:h-10 sm:text-sm ${recommended ? 'bg-violet-600 hover:bg-violet-700' : ''}`} disabled={Boolean(loadingPlan)} onClick={() => void createPayment(plan.id)} type="button" variant={recommended ? 'default' : 'outline'}>
                      {loadingPlan === plan.id ? <Loader2 className="size-4 animate-spin" /> : `Chọn gói ${plan.duration_days} ngày`}
                    </Button>
                  </article>
                )
              })}
            </div>
          </div>
        )}
        {error ? <p className="text-sm font-semibold text-red-600">{error}</p> : null}
      </DialogContent>
    </Dialog>
  )
}
